"File: Video":
- '**/*.mp4'
- '**/*.mov'

"File: Audio":
- '**/*.mp3'
- '**/*.ogg'
- 'Server content/Resources/Audio/**'

"File: Text":
- '**/*.txt'

"File: Textures":
- 'Server content/Resources/Textures/**'
- '**/meta.json'

"File: github":
- '.github/**'

"File: Role":
- 'Server content/Resources/Prototypes/Roles/**'

"File: Localization":
- '**/*.ftl'

"File: Entity":
- 'Server content/Resources/Prototypes/Entities/**'

"File: PROJECT EXCLUSIVE":
- 'Server content/**/mark'
- 'Server content/**/Bluespace-content/**'

"NOT TO MERGE":
- '**/SECURITY.md'
- '**/LICENSE.txt'