- type: job
  id: Blueshield
  name: job-name-blueshield  
  description: job-description-blueshield  
  playTimeTracker: JobBlueshield  
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 54000 # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Security
      time: 54000 # Corvax-RoleTime
    - !type:OverallPlaytimeRequirement
      time: 648000 # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Command
      time: 54000
  weight: 20
  startingGear: BlueshieldGear
  icon: "Blueshield"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: BlueshieldGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBlueshield 
    back: ClothingBackpackBlueshieldFilled 
    shoes: ClothingShoesColorBlack
    head: ClothingHeadHatCaptain
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesBlueshield 
    outerClothing: ClothingOuterVestArmorSec 
    id: BlueshieldPDA 
    ears: ClothingHeadsetBlueshield 
  innerclothingskirt: ClothingUniformJumpskirtBlueshield 
